DROP DATABASE IF EXISTS LMSDB;

CREATE DATABASE LMSDB;
USE LMSDB;

/* Table = USER */

DROP TABLE IF EXISTS `USERS`;
CREATE TABLE IF NOT EXISTS `USERS` (
  `USERID` INT NOT NULL,
  `NAME` varchar(64) NOT NULL,
  `EMAIL` varchar(64) NOT NULL,
  `DEPARTMENT` varchar(64) NOT NULL,
  `DESIGNATION` varchar(64) NOT NULL, 
  PRIMARY KEY (`USERID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = ADMINS */
DROP TABLE IF EXISTS `ADMINS`;
CREATE TABLE IF NOT EXISTS `ADMINS` (
  `USERID` INT NOT NULL,
  PRIMARY KEY (`USERID`),
  CONSTRAINT FK_ADMINS FOREIGN KEY (USERID) REFERENCES USERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = TRAINERS */
DROP TABLE IF EXISTS `TRAINERS`;
CREATE TABLE IF NOT EXISTS `TRAINERS` (
  `USERID` INT NOT NULL,
  PRIMARY KEY (`USERID`),
  CONSTRAINT FK_TRAINERS FOREIGN KEY (USERID) REFERENCES USERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = LEARNERS */
DROP TABLE IF EXISTS `LEARNERS`;
CREATE TABLE IF NOT EXISTS `LEARNERS` (
  `USERID` INT NOT NULL,
  PRIMARY KEY (`USERID`),
  CONSTRAINT FK_LEARNERS FOREIGN KEY (USERID) REFERENCES USERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = COURSE */
DROP TABLE IF EXISTS `COURSE`;
CREATE TABLE IF NOT EXISTS `COURSE` (
  `COURSE_ID` INT NOT NULL,
  `COURSE_NAME` VARCHAR(64) NOT NULL,
  `COURSE_DESCRIPTION` VARCHAR(255),
  `BADGENUM` INT NOT NULL,
  `STARTDATE` DATETIME NOT NULL,
  `ENDDATE` DATETIME NOT NULL,
  `STARTENROLLMENTDATE` DATETIME,
  `ENDENROLLMENTDATE` DATETIME,
  PRIMARY KEY (`COURSE_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = Course_Prerequisite */
DROP TABLE IF EXISTS `COURSE_PREREQUISITE`;
CREATE TABLE IF NOT EXISTS `COURSE_PREREQUISITE` (
  `COURSE_ID` INT NOT NULL,
  `PREREQ_COURSE_ID` INT NOT NULL,
  PRIMARY KEY (`COURSE_ID`, `PREREQ_COURSE_ID`),
  CONSTRAINT FK_PREREQ FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
  CONSTRAINT FK_PREREQ2 FOREIGN KEY (PREREQ_COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = LEARNER_COMPLETED_COURSE */
DROP TABLE IF EXISTS `LEARNER_BADGES`;
CREATE TABLE IF NOT EXISTS `LEARNER_BADGES` (
  `USERID` INT NOT NULL,
  `COURSE_ID` INT NOT NULL,
  PRIMARY KEY (`USERID`, `COURSE_ID`),
  CONSTRAINT FK_LEARNER_BADGES FOREIGN KEY (USERID) REFERENCES USERS(USERID),
  CONSTRAINT FK_LEARNER_BADGES2 FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



/* Table = CLASSES */
DROP TABLE IF EXISTS `CLASSES`;
CREATE TABLE IF NOT EXISTS `CLASSES` (
  `COURSE_ID` INT NOT NULL,
  `CLASS_ID` INT NOT NULL AUTO_INCREMENT,
  `SLOTS` INT NOT NULL,
  PRIMARY KEY ( `CLASS_ID` ),
  CONSTRAINT FK_CLASSES FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = SECTIONS */
DROP TABLE IF EXISTS `SECTIONS`;
CREATE TABLE IF NOT EXISTS `SECTIONS` (
  `SECTION_ID` INT NOT NULL AUTO_INCREMENT,
  `CLASS_ID` INT NOT NULL,
  PRIMARY KEY ( `SECTION_ID` ),
  CONSTRAINT FK_SECTIONS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = VIEWABLE_SECTION */
DROP TABLE IF EXISTS `VIEWABLE_SECTION`;
CREATE TABLE IF NOT EXISTS `VIEWABLE_SECTION` (
  `SECTION_ID` INT NOT NULL,
  `USERID` INT NOT NULL,
  `CLASS_ID` INT NOT NULL,
  `VIEWABLE` BOOLEAN,
  PRIMARY KEY ( `SECTION_ID`, `CLASS_ID`, `USERID` ),
  CONSTRAINT FK_VIEWABLE_SECTIONS FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
  CONSTRAINT FK_VIEWABLE_SECTIONS2 FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS(SECTION_ID),
  CONSTRAINT FK_VIEWABLE_SECTIONS3 FOREIGN KEY (USERID) REFERENCES LEARNERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = SECTION_MATERIALS */
DROP TABLE IF EXISTS `SECTION_MATERIALS`;
CREATE TABLE IF NOT EXISTS `SECTIONS` (
  `SECTION_ID` INT NOT NULL,
  `MATERIAL_ID` INT NOT NULL AUTO_INCREMENT,
  `MATERIAL_Title` TEXT,
  `MATERIAL_CONTENT` TEXT,
  PRIMARY KEY ( `MATERIAL_ID` ),
  CONSTRAINT FK_SECTIONS_MATERIALS FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS(SECTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;



/* Table = QUIZZES */
DROP TABLE IF EXISTS `QUIZZES`;
CREATE TABLE IF NOT EXISTS `QUIZZES` (
  `QUIZ_ID` INT NOT NULL AUTO_INCREMENT,
  `SECTION_ID` INT NOT NULL,
  `TIME_LIMIT` INT NOT NULL,
  PRIMARY KEY ( `QUIZ_ID`, `SECTION_ID` ),
  CONSTRAINT FK_QUIZZES FOREIGN KEY (SECTION_ID) REFERENCES SECTIONS(SECTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = QUIZ_QUESTION */
DROP TABLE IF EXISTS `QUIZ_QUESTION`;
CREATE TABLE IF NOT EXISTS `QUIZ_QUESTION` (
  `QUESTION_ID` INT NOT NULL AUTO_INCREMENT,
  `QUIZ_ID` INT NOT NULL,
  `QORDER` INT NOT NULL,
  `QUESTION` TEXT ,
  PRIMARY KEY (`QUESTION_ID`),
  CONSTRAINT FK_QUIZ_QUESTION FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = MCQ_OPTIONS */
DROP TABLE IF EXISTS `MCQ_OPTIONS`;
CREATE TABLE IF NOT EXISTS `MCQ_OPTIONS` (
  `QUESTION_ID` INT NOT NULL,
  `OPTION_ORDER` INT NOT NULL,
  `OPTION_CONTENT` TEXT NOT NULL,
  PRIMARY KEY ( `QUESTION_ID`, `OPTION_ORDER` ),
  CONSTRAINT FK_MCQ_OPTIONS FOREIGN KEY (QUESTION_ID) REFERENCES QUIZ_QUESTION(QUESTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = TrueFalseQ */
DROP TABLE IF EXISTS `TrueFalseQ`;
CREATE TABLE IF NOT EXISTS `TrueFalseQ` (
  `QUESTION_ID` INT NOT NULL,
  `ANSWER` varchar(64) NOT NULL,
  PRIMARY KEY ( `QUESTION_ID`),
  CONSTRAINT FK_TrueFalseQ FOREIGN KEY (QUESTION_ID) REFERENCES QUIZ_QUESTION(QUESTION_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = FINAL_QUIZ */
DROP TABLE IF EXISTS `FINAL_QUIZ`;
CREATE TABLE IF NOT EXISTS `FINAL_QUIZ` (
  `QUIZ_ID` INT NOT NULL,
  `PASSING_SCORE` INT NOT NULL,
  PRIMARY KEY (`QUIZ_ID`),
  CONSTRAINT FK_FINALQ FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/* Table = QUIZ_SCORE */
DROP TABLE IF EXISTS `QUIZ_SCORE`;
CREATE TABLE IF NOT EXISTS `QUIZ_SCORE` (
  `QUIZ_ID` INT NOT NULL,
  `USERID` INT NOT NULL,
  PRIMARY KEY (`QUIZ_ID`, `USERID` ),
  CONSTRAINT FK_QUIZ_SCORE FOREIGN KEY (QUIZ_ID) REFERENCES QUIZZES(QUIZ_ID),
  CONSTRAINT FK_QUIZ_SCORE2 FOREIGN KEY (USERID) REFERENCES USERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


/* Table = TRAINERASSIGNMENT */
DROP TABLE IF EXISTS `TRAINERASSIGNMENT`;
CREATE TABLE IF NOT EXISTS `TRAINERASSIGNMENT` (
  `COURSE_ID` INT NOT NULL,
  `CLASS_ID` INT NOT NULL,
  `USERID` INT NOT NULL,
  PRIMARY KEY (`COURSE_ID`,`USERID`,`CLASS_ID`),
  CONSTRAINT FK_TRAINASSIGNMENT FOREIGN KEY (CLASS_ID) REFERENCES CLASSES(CLASS_ID),
  CONSTRAINT FK_TRAINASSIGNMENT2 FOREIGN KEY (COURSE_ID) REFERENCES COURSE(COURSE_ID),
  CONSTRAINT FK_TRAINASSIGNMENT3 FOREIGN KEY (USERID) REFERENCES TRAINERS(USERID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
